export const COFOUNDER_TYPE_OPTIONS = [
  { value: "ceo", label: "GĐ Điều hành" },
  {
    value: "cto",
    label: "GĐ Công nghệ",
  },
  { value: "cfo", label: "GĐ Tài chính" },
  { value: "cmo", label: "GĐ Marketing" },
  { value: "coo", label: "GĐ Vận hành" },
  { value: "cpo", label: "GĐ Sản phẩm" },
  { value: "cso", label: "GĐ Chiến lược" },
  { value: "cdo", label: "GĐ Thiết kế" },
  { value: "cio", label: "GĐ Đổi mới" },
  {
    value: "business_cofounder",
    label: "Sáng lập Kinh doanh",
  },
  {
    value: "technical_cofounder",
    label: "Sáng lập Kỹ thuật",
  },
  {
    value: "marketing_cofounder",
    label: "Sáng lập Marketing",
  },
  {
    value: "product_cofounder",
    label: "Sáng lập Sản phẩm",
  },
  {
    value: "sales_cofounder",
    label: "Sáng lập Bán hàng",
  },
  {
    value: "growth_hacker_cofounder",
    label: "Sáng lập Tăng trưởng",
  },
  {
    value: "design_cofounder",
    label: "Sáng lập Thiết kế",
  },
  {
    value: "part_time_cofounder",
    label: "Sáng lập Bán thời gian",
  },
  {
    value: "STATION_OWNER_cofounder",
    label: "Sáng lập Nhà đầu tư",
  },
  { value: "other", label: "Khác" },
];

export const PARTNER_TYPE_OPTIONS = [
  {
    value: "strategic_partner",
    label: "Đối tác chiến lược",
  },
  {
    value: "technology_partner",
    label: "Đối tác công nghệ",
  },
  {
    value: "distribution_partner",
    label: "Đối tác phân phối",
  },
  { value: "sales_partner", label: "Đối tác bán hàng" },
  { value: "marketing_partner", label: "Đối tác tiếp thị" },
  {
    value: "manufacturing_partner",
    label: "Đối tác sản xuất",
  },
  {
    value: "ecommerce_partner",
    label: "Đối tác TMĐT",
  },
  {
    value: "financial_banking_partner",
    label: "Đối tác tài chính",
  },
  {
    value: "logistics_partner",
    label: "Đối tác vận chuyển",
  },
  { value: "legal_partner", label: "Đối tác pháp lý" },
  {
    value: "hr_recruitment_partner",
    label: "Đối tác nhân sự",
  },
  {
    value: "training_education_partner",
    label: "Đối tác đào tạo",
  },
  { value: "media_partner", label: "Đối tác truyền thông" },
  {
    value: "community_partner",
    label: "Đối tác cộng đồng",
  },
  {
    value: "supply_chain_partner",
    label: "Đối tác cung ứng",
  },
  {
    value: "b2b_partner",
    label: "Đối tác B2B",
  },
  {
    value: "b2c_partner",
    label: "Đối tác B2C",
  },
  {
    value: "win_win_collaboration",
    label: "Hợp tác đôi bên",
  },
  {
    value: "white_label_partner",
    label: "Đối tác không thương hiệu",
  },
  {
    value: "affiliate_partner",
    label: "Đối tác liên kết",
  },
  { value: "other", label: "Khác" },
];

export const PROJECT_CATEGORY_OPTIONS = [
  { value: "food_beverage", label: "Ẩm thực" },
  { value: "technology_engineering", label: "Công nghệ" },
  { value: "information_technology", label: "CNTT" },
  { value: "web2", label: "Web2" },
  { value: "web3", label: "Web3" },
  { value: "electrical_electronics", label: "Điện tử" },
  { value: "tourism_culinary", label: "Du lịch" },
  { value: "entertainment", label: "Giải trí" },
  { value: "education", label: "Giáo dục" },
  { value: "transportation", label: "Giao thông" },
  { value: "business", label: "Kinh doanh" },
  { value: "environment", label: "Môi trường" },
  { value: "agriculture_forestry_fishery", label: "Nông nghiệp" },
  { value: "advertising", label: "Quảng cáo" },
  { value: "event_culture_art", label: "Sự kiện" },
  { value: "health", label: "Sức khỏe" },
  { value: "fashion", label: "Thời trang" },
  { value: "handicrafts", label: "Thủ công" },
  { value: "savings", label: "Tiết kiệm" },
  { value: "news", label: "Tin tức" },
  { value: "culture_art", label: "Văn hóa nghệ thuật" },
  { value: "telecommunications", label: "Viễn thông" },
  {
    value: "social_community_environment",
    label: "Cộng đồng",
  },
  { value: "medical_healthcare", label: "Y tế" },
  { value: "other_ideas", label: "Khác" },
];

export const PROJECT_FUNDING_STAGE_OPTIONS = [
  { value: "pre_seed", label: "Pre-seed" },
  { value: "seed", label: "Seed" },
  { value: "series_a", label: "Series A" },
  { value: "series_b", label: "Series B" },
  { value: "series_c", label: "Series C" },
  { value: "series_d_plus", label: "Series D+" },
  { value: "ipo", label: "IPO" },
  { value: "acquired", label: "Acquired (Đã được mua lại)" },
  { value: "profitable", label: "Profitable (Đã có lợi nhuận)" },
  {
    value: "bootstrapped",
    label: "Bootstrapped (Tự lực, không gọi vốn ngoài)",
  },
  { value: "crowdfunding", label: "Crowdfunding (Gọi vốn cộng đồng)" },
  { value: "grant", label: "Grant (Nhận tài trợ)" },
  { value: "other", label: "Other / Khác" },
];

export const PROFILE_TYPE_OPTIONS = [
  { value: "CUSTOMER", label: "Người dùng cá nhân" },
  { value: "STATION_OWNER", label: "Quản lý trạm sạc" },
  { value: "TECHNICIAN", label: "Kỹ thuật viên" },
];

export const PROFILE_ROLE_OPTIONS = [
  { value: "ceo", label: "GĐ Điều hành" },
  { value: "co_founder", label: "Đồng sáng lập" },
  { value: "founder", label: "Nhà sáng lập" },
  { value: "cto", label: "GĐ Công nghệ" },
  { value: "cmo", label: "GĐ Marketing" },
  { value: "cfo", label: "GĐ Tài chính" },
  { value: "project_manager", label: "QL Dự án" },
  {
    value: "investment_analyst_profile",
    label: "Phân tích đầu tư",
  },
  { value: "STATION_OWNER_profile", label: "Nhà đầu tư" },
  { value: "partner_profile", label: "Đối tác đầu tư" },
  { value: "mentor_profile", label: "Cố vấn" },
  { value: "legal_advisor", label: "Tư vấn pháp lý" },
  {
    value: "marketing_specialist",
    label: "Chuyên viên MKT",
  },
  { value: "developer", label: "Lập trình viên" },
  { value: "product_designer", label: "Thiết kế" },
  {
    value: "business_analyst",
    label: "Phân tích nghiệp vụ",
  },
  { value: "sales_manager", label: "QL Kinh doanh" },
  {
    value: "operations_manager",
    label: "QL Vận hành",
  },
  { value: "researcher_profile", label: "Nghiên cứu" },
  { value: "lecturer", label: "Giảng viên" },
  {
    value: "organization_representative",
    label: "Đại diện tổ chức",
  },
  { value: "consultant_profile", label: "Tư vấn viên" },
  { value: "assistant", label: "Trợ lý" },
  { value: "student", label: "Sinh viên" },
  { value: "other_role", label: "Khác" },
];

export const VIETNAM_LOCATIONS = [
  "An Giang",
  "Bà Rịa - Vũng Tàu",
  "Bạc Liêu",
  "Bắc Giang",
  "Bắc Kạn",
  "Bắc Ninh",
  "Bến Tre",
  "Bình Dương",
  "Bình Định",
  "Bình Phước",
  "Bình Thuận",
  "Cà Mau",
  "Cao Bằng",
  "Cần Thơ (TP)",
  "Đà Nẵng (TP)",
  "Đắk Lắk",
  "Đắk Nông",
  "Điện Biên",
  "Đồng Nai",
  "Đồng Tháp",
  "Gia Lai",
  "Hà Giang",
  "Hà Nam",
  "Hà Nội (TP)",
  "Hà Tĩnh",
  "Hải Dương",
  "Hải Phòng (TP)",
  "Hậu Giang",
  "Hòa Bình",
  "Hưng Yên",
  "Khánh Hòa",
  "Kiên Giang",
  "Kon Tum",
  "Lai Châu",
  "Lâm Đồng",
  "Lạng Sơn",
  "Lào Cai",
  "Long An",
  "Nam Định",
  "Nghệ An",
  "Ninh Bình",
  "Ninh Thuận",
  "Phú Thọ",
  "Phú Yên",
  "Quảng Bình",
  "Quảng Nam",
  "Quảng Ngãi",
  "Quảng Ninh",
  "Quảng Trị",
  "Sóc Trăng",
  "Sơn La",
  "Tây Ninh",
  "Thái Bình",
  "Thái Nguyên",
  "Thanh Hóa",
  "Thừa Thiên Huế",
  "Tiền Giang",
  "TP. Hồ Chí Minh (TP)",
  "Trà Vinh",
  "Tuyên Quang",
  "Vĩnh Long",
  "Vĩnh Phúc",
  "Yên Bái",
];
